### ISSUE TITLE
Unable to use the custom service for jellyfin

### ISSUE THREAD

**Issue by tomerh2001** [bastienwirtz/homer#629]
**Describe the bug**
Modified my jellyfin item to as following:
```
      - name: "Jellyfin"
        subtitle: "Media Streaming/Management"
        logo: "assets/tools/jellyfin.png"
        url: "https://jellyfin.domain.com/"
        tag: "media"
        type: "emby"
        apikey: "x"
        libraryType: "Movies"
```

Then after refreshing, the jellyfin item dissapered and I got the following error in the chrome console:
```
dex.32f5632b.js:1 Error: Unknown variable dynamic import: ./services/emby.vue
    at index.32f5632b.js:126:17022
    at new Promise (<anonymous>)
    at kd (index.32f5632b.js:126:16928)
    at index.32f5632b.js:126:18675
    at y (index.32f5632b.js:1:19562)
    at setup (index.32f5632b.js:1:20253)
    at Tt (index.32f5632b.js:1:12652)
    at tu (index.32f5632b.js:1:46905)
    at eu (index.32f5632b.js:1:46690)
    at Fe (index.32f5632b.js:1:36356)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/45624804/233185126-79b77ac0-a27a-4334-88f1-72c462b1dfa3.png)

Jellyfin used to be the first item in the media group.

**Comment by tanasegabriel** [comment]
Hey @tomerh2001 👋 Apologies for the very long delay on this one.

@crwallace2 is right, and thanks for spotting it. `type` is case sensitive: it maps directly onto a component filename, so `Emby` resolves to `Emby.vue` while `emby` matches nothing, which is what that "Unknown variable dynamic import" error is telling you.

There is a second case issue in your snippet that would have caught you out right after fixing the first. `libraryType` is matched against the lowercase values `music`, `movies` and `series`, so `Movies` falls through and the card renders the text `wrong library type 💀` instead of your movie count. Both together:

```yaml
- name: "Jellyfin"
  subtitle: "Media Streaming/Management"
  logo: "assets/tools/jellyfin.png"
  url: "https://jellyfin.domain.com/"
  tag: "media"
  type: "Emby"
  apikey: "x"
  libraryType: "movies"
```

Closing on that basis, but please feel free to reopen if `Emby` plus `movies` still does not work for you.
