### ISSUE TITLE
Bugs with UptimeKuma service

### ISSUE THREAD

**Issue by ThowZzy** [bastienwirtz/homer#690]
**Describe the bug**
UptimeKuma service have some issues.
The first bug is when changing the type of list from homer (column or on a line), when changing the type, the pourcentage of uptime disapear with the error in the console: 
```SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data UptimeKuma-e81b5dce.js:1:1571
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data UptimeKuma-e81b5dce.js:1:1697
```

The second bug is when I clear both EVENTS and HEARTBEATS from a monitored service on UptimeKuma, then when viewing Homer, the service UptimeKuma completely disappear with this log in console:
```TypeError: this.lastHeartBeatList[a] is undefined
    pageStatus https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    get value https://xx.be/resources/index-e8cbcd37.js:1
    get https://xx.be/resources/index-e8cbcd37.js:1
    get https://xx.be/resources/index-e8cbcd37.js:1
    status https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    get value https://xx.be/resources/index-e8cbcd37.js:1
    get https://xx.be/resources/index-e8cbcd37.js:1
    indicator https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    s https://xx.be/resources/index-e8cbcd37.js:1
    Dn https://xx.be/resources/index-e8cbcd37.js:1
    qd https://xx.be/resources/index-e8cbcd37.js:129
    di https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    il https://xx.be/resources/index-e8cbcd37.js:1
    promise callback*nl https://xx.be/resources/index-e8cbcd37.js:1
    js https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    pt https://xx.be/resources/index-e8cbcd37.js:1
    Vo https://xx.be/resources/index-e8cbcd37.js:1
    set https://xx.be/resources/index-e8cbcd37.js:1
    fetchStatus https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    promise callback*fetchStatus https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    created https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    Ze https://xx.be/resources/index-e8cbcd37.js:1
    Ze https://xx.be/resources/index-e8cbcd37.js:1
    Zr https://xx.be/resources/index-e8cbcd37.js:1
    Rf https://xx.be/resources/index-e8cbcd37.js:1
    El https://xx.be/resources/index-e8cbcd37.js:1
    au https://xx.be/resources/index-e8cbcd37.js:1
    lu https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    il https://xx.be/resources/index-e8cbcd37.js:1
    promise callback*nl https://xx.be/resources/index-e8cbcd37.js:1
    js https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    set value https://xx.be/resources/index-e8cbcd37.js:1
    setup https://xx.be/resources/index-e8cbcd37.js:1
    promise callback*setup https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    au https://xx.be/resources/index-e8cbcd37.js:1
    lu https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Te https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    I https://xx.be/resources/index-e8cbcd37.js:1
    B https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    Oe https://xx.be/resources/index-e8cbcd37.js:1
    ge https://xx.be/resources/index-e8cbcd37.js:1
    B https://xx.be/resources/index-e8cbcd37.js:1
index-e8cbcd37.js:1:13148
    rf https://xx.be/resources/index-e8cbcd37.js:1
    Jn https://xx.be/resources/index-e8cbcd37.js:1
    di https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    il https://xx.be/resources/index-e8cbcd37.js:1
    (Asynchrone : promise callback)
    nl https://xx.be/resources/index-e8cbcd37.js:1
    js https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    pt https://xx.be/resources/index-e8cbcd37.js:1
    Vo https://xx.be/resources/index-e8cbcd37.js:1
    set https://xx.be/resources/index-e8cbcd37.js:1
    fetchStatus https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    (Asynchrone : promise callback)
    fetchStatus https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    created https://xx.be/resources/UptimeKuma-e81b5dce.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    Ze https://xx.be/resources/index-e8cbcd37.js:1
    Ze https://xx.be/resources/index-e8cbcd37.js:1
    Zr https://xx.be/resources/index-e8cbcd37.js:1
    Rf https://xx.be/resources/index-e8cbcd37.js:1
    El https://xx.be/resources/index-e8cbcd37.js:1
    au https://xx.be/resources/index-e8cbcd37.js:1
    lu https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    il https://xx.be/resources/index-e8cbcd37.js:1
    (Asynchrone : promise callback)
    nl https://xx.be/resources/index-e8cbcd37.js:1
    js https://xx.be/resources/index-e8cbcd37.js:1
    effect https://xx.be/resources/index-e8cbcd37.js:1
    qr https://xx.be/resources/index-e8cbcd37.js:1
    Ci https://xx.be/resources/index-e8cbcd37.js:1
    Zo https://xx.be/resources/index-e8cbcd37.js:1
    set value https://xx.be/resources/index-e8cbcd37.js:1
    setup https://xx.be/resources/index-e8cbcd37.js:1
    (Asynchrone : promise callback)
    setup https://xx.be/resources/index-e8cbcd37.js:1
    Et https://xx.be/resources/index-e8cbcd37.js:1
    au https://xx.be/resources/index-e8cbcd37.js:1
    lu https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    N https://xx.be/resources/index-e8cbcd37.js:1
    run https://xx.be/resources/index-e8cbcd37.js:1
    update https://xx.be/resources/index-e8cbcd37.js:1
    Te https://xx.be/resources/index-e8cbcd37.js:1
    Sn https://xx.be/resources/index-e8cbcd37.js:1
    Ht https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    oe https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    X https://xx.be/resources/index-e8cbcd37.js:1
    I https://xx.be/resources/index-e8cbcd37.js:1
    B https://xx.be/resources/index-e8cbcd37.js:1
    g https://xx.be/resources/index-e8cbcd37.js:1
    Oe https://xx.be/resources/index-e8cbcd37.js:1
    ge https://xx.be/resources/index-e8cbcd37.js:1
    B https://xx.be/resources/index-e8cbcd37.js:1
```

**Expected behavior**
No bugs

**Logs & errors**
included

**Screenshots**
![image](https://github.com/bastienwirtz/homer/assets/61882536/f2cd2eec-706c-4ba4-83ef-d538a64a716f)
![image](https://github.com/bastienwirtz/homer/assets/61882536/56f5aa4a-7296-4665-8ab2-ecedc5a2f78a)
(no screenshot for the second bug because it just disappear)

**Configuration**
If applicable, copy related homer yaml configuration here.
```yml
- name: "Uptime"
        logo: "assets/icons/uptimekuma.png"
        subtitle: "uptime.xx"
        keyword: "monitoring"
        tag: "monitoring"
        url: "https://uptime.xx"
        slug: "uptime"
        type: "UptimeKuma"
```

**Comment by tanasegabriel** [comment]
Hey 👋 Sorry this went stale. The first bug is fixed, pending a new release. The root cause write up is in #1056.

Your second report, the `this.lastHeartBeatList[a] is undefined` crash after clearing events and heartbeats, is a separate path and I have not verified whether it still reproduces on current versions of both Homer and Uptime Kuma. Rather than keep this issue open covering two unrelated things, I would suggest closing here and opening a fresh one if you can still trigger it on a recent version. A fresh report would be much easier to act on than a three year old one, especially if you could try to reproduce it after we get the next version of Homer released.

**Comment by bastienwirtz** [comment]
Thanks @tanasegabriel for looking into it! Let's close this one and follow your suggestion 🙏
