### ISSUE TITLE
Breaking change with Immich 1.85 and Homer custom service

### ISSUE THREAD

**Issue by muzzymate** [bastienwirtz/homer#719]
**Describe the bug**
The custom service for Immich utilizes the endpoint /server-info/stats. In Immich 1.85, the endpoint has been changed to /server-info/statistics. As a result, when Homer calls the Immich API endpoint, the server responds with a 404. 

Immich 1.85 release notes: https://github.com/immich-app/immich/releases/tag/v1.85.0

**Expected behavior**
The custom service for Immich utilizes the updated endpoint URL.

**Logs & errors**
Browser console log:

        GET http://photos.server.local/api/server-info/stats net::ERR_FAILED 404 (Not Found)
fetch @ service-56521882.js:1
fetchConfig @ Immich-7be309fe.js:1
(anonymous) @ Immich-7be309fe.js:1
Immich-7be309fe.js:1  TypeError: Failed to fetch
    at Proxy.fetch (service-56521882.js:1:496)
    at Proxy.fetchConfig (Immich-7be309fe.js:1:737)
    at Immich-7be309fe.js:1:391
(anonymous) @ Immich-7be309fe.js:1
Promise.catch (async)
fetchConfig @ Immich-7be309fe.js:1
(anonymous) @ Immich-7be309fe.js:1

**Comment by muzzymate** [comment]
Confirming that I was able to correct on my local by changing the url from stats to statistics. The four information bubbles now show expected numbers. 

Unfortunately, I'm not a coder, so implementing in a smart way to have the URL attempted be dynamic to what version of Immich is beyond my ability. But was able to accomplish by editing the Immich-7be309fe.js in the Docker image, changing 

`this.fetch("/api/server-info/stats"` to `this.fetch("/api/server-info/statistics"`
